repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: check-forbidden-files
        name: Check forbidden files
        entry: python scripts/check_forbidden_files.py
        language: python
        pass_filenames: false
        always_run: true
